enum class TokenType {
  PARENTESE_ESQUERDO, PARENTESE_DIREITO, CHAVE_ESQUERDA, CHAVE_DIREITA, COLCHETE_DIREITO, COLCHETE_ESQUERDO,
  VIRGULA, PONTO, MENOS, MAIS, PONTOEVIRGULA, BARRA, ASTERISCO, MAIS_MAIS, MENOS_MENOS,
  PORCENTAGEM,ECOMERCIAL, ACENTOCHAPEU, BARRAV, TIL,

  BANG, BANG_IGUAL,
  IGUAL, IGUAL_IGUAL,
  MAIOR, MAIOR_IGUAL, MAIOR_MAIOR,
  MENOR, MENOR_IGUAL, MENOR_MENOR,

  IDENTIFICAR, TEXTO, NUMERO, INCLUIR,

  E, CLASSE, SENAO, FALSO, DEFINIR, POR, SE, NULO, OU, SAID,
  SAIDA, RETORNE, SUPER, ISSO, VERDADEIRO, VAR, ENQUANTO,

  NX_EOF 
};

