import string

TT_INT = "TT_INT"
TT_FLOAT = "TT_FLOAT"
TT_STRING = "TT_STRING"
TT_IDENTIFIER = "TT_IDENTIFIER"
TT_KEYWORD = "TT_KEYWORD"
TT_PLUS = "TT_PLUS"
TT_MINUS = "TT_MINUS"
TT_MUL = "TT_MUL"
TT_DIV = "TT_DIV"
TT_MOD = "TT_MOD"
TT_FLOORDIV = "TT_FLOORDIV"
TT_POW = "TT_POW"
TT_EQ = "TT_EQ"
TT_LPAREN = "TT_LPAREN"
TT_RPAREN = "TT_RPAREN"
TT_LBRACE = "TT_LBRACE"
TT_RBRACE = "TT_RBRACE"
TT_COMMA = "TT_COMMA"
TT_DOT = "TT_DOT"
TT_EE = "TT_EE"
TT_NE = "TT_NE"
TT_LT = "TT_LT"
TT_GT = "TT_GT"
TT_LTE = "TT_LTE"
TT_GTE = "TT_GTE"
TT_EOF = "TT_EOF"
TT_LSQUARE = "TT_LSQUARE"
TT_RSQUARE = "TT_RSQUARE"
TT_PLUSPLUS = "TT_PLUSPLUS"
TT_MINUSMINUS = "TT_MINUSMINUS"
TT_COLON = "TT_COLON"
TT_PLUSEQ = "PLUSEQ"
TT_MINUSEQ = "MINUSEQ"
TT_MULEQ = "MULEQ"
TT_DIVEQ = "DIVEQ"
TT_POWEQ = "POWEQ"
TT_MODEQ = "MODEQ"
TT_FLOORDIVEQ = "FLOORDIVEQ"

KEYWORDS = [
    "DECLARAR",
    "FINAL",
    "IMPRIMIR",
    "SE",
    "ENTAO",
    "SENAO",
    "FIMSE",
    "E",
    "OU",
    "NAO",
    "FUNCAO",
    "FIMFUNCAO",
    "RETORNAR",
    "CLASSE",
    "FIMCLASSE",
    "HERDA",
    "NOVO",
    "EU",
    "ENQUANTO",
    "FIMENQUANTO",
    "PARAR",
    "CONTINUAR",
    "PARA",
    "EM",
    "FIMPARA",
    "TENTE",
    "CAPTURAR",
    "FINALMENTE",
    "FIMTENTE",
    "LANCAR",
    "ESCOLHA",
    "CASO",
    "PADRAO",
    "FIMESCOLHA",
    "ser",
    "e",
    "ou",
]


DIGITS = "0123456789"
LETTERS = string.ascii_letters
LETTERS_DIGITS = LETTERS + DIGITS
